version: '3'
services:
  app:
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: unless-stopped
    volumes:
      - app:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - ${DB_PORT}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  app:
  db:

networks:
  postgres:
    driver: bridge